### ISSUE TITLE
TypeError: expected string or bytes-like object, got 'PosixPath'

### ISSUE THREAD

**Issue by odisseus** [simplistix/testfixtures#189]
I have a piece of code that looks like this:
```python
args = [Path("/path/to/executable"), "foo", "bar", "baz"]
...
process = subprocess.Popen(args, ...)
```
I want to mock the `/path/to/executable` call for testing purposes, because it is quite costly. In my test code, the mock looks like this:
```python
self.Popen = MockPopen()
self.r = Replacer()
self.r.replace("my.module.name.subprocess.Popen", self.Popen)
self.Popen.set_command(
  "/path/to/executable foo bar baz",
  stdout=b"fake output"),
  stderr=b"fake error"),
  poll_count=1
)
```
When I run the test, I get the following exception:
```
s = PosixPath('/path/to/executable')

    def quote(s):
        """Return a shell-escaped version of the string *s*."""
        if not s:
            return "''"
>       if _find_unsafe(s) is None:
E       TypeError: expected string or bytes-like object, got 'PosixPath'

/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shlex.py:329: TypeError
```

However, when I change the first element of my `args` list from `Path("/path/to/executable")` to `"/path/to/executable"`, the test completes without errors.

As far as I understand, the first argument of `subprocess.Popen` is allowed to be a `PosixPath`, so this looks like a bug in this package.

Mac OS 14.0, Python 3.11.5, testfixtures 7.2.0.

**Comment by cjw296** [comment]
Fixed in https://github.com/simplistix/testfixtures/commit/b814a3a06f2ecf9e68d73b4e955e20ad19695b52

**Comment by cjw296** [comment]
Released in https://pypi.org/project/testfixtures/7.2.1/

**Comment by odisseus** [comment]
It still doesn't work. With the version 7.2.1, I get this error:
```

command = [PosixPath('/path/to/executable'), 'foo', 'bar', 'baz']

    def shell_join(command: Command) -> str:
        if isinstance(command, str):
            return command
        elif isinstance(command, PathLike):
            return str(command)
        elif isinstance(command, Iterable):
            quoted_parts = []
            for part in command:
                if not isinstance(part, str):
>                   raise TypeError(f'{part!r} in {command} was {type(part)}, must be str')
E                   TypeError: PosixPath('/path/to/executable') in [PosixPath('/path/to/executable'), 'foo', 'bar', 'baz'] was <class 'pathlib.PosixPath'>, must be str

../.venv/lib/python3.11/site-packages/testfixtures/popen.py:26: TypeError
```

**Comment by cjw296** [comment]
Managed to miss your actual case 🤦 
Fixed in ed32ea4c7867745304c475c444e63efd3cb1ab84

**Comment by cjw296** [comment]
Fixed in https://pypi.org/project/testfixtures/7.2.2/

**Comment by odisseus** [comment]
Now that's a quick response! Thank you!

Technically, there's still a possibility of arguments that are neither strings nor paths, but I can't think of any good reason to write such code in the first place, and the current solution works in my particular case.

**Comment by cjw296** [comment]
I'm not sure it's valid to send anything other than paths or strings to the `POpen` constructor, can you point me to documentation suggesting otherwise?

**Comment by cjw296** [comment]
Okay, I've covered these in 34379d84e9bd4d5c83f672422d622d8a23954a49. I'll release if anyone specifically needs this before there's a release for another reason :-)
